name: e2e_schedule

on:
  # refer: https://crontab.guru/examples.html
  # 14:00 is us time
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

env:
  KUKEAN_OPERATOR_IMAGE_NAME: kubean-operator
  KUBESPRAY_IMAGE_NAME: kubespray
  SPRAY_JOB_IMAGE_NAME: spray-job
  KUBESPRAY_TAG: latest
  VSPHERE_USER: ${{ secrets.VSPHERE_USER }}
  VSPHERE_PASSWD: ${{ secrets.VSPHERE_PASSWD }}
  AMD_ROOT_PASSWORD: ${{ secrets.AMD_ROOT_PASSWORD }}
  KYLIN_VM_PASSWORD: ${{ secrets.KYLIN_VM_PASSWORD }}
  
jobs:
  build-push-for-e2e:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set env
        run: |
          ORGANIZATION_NAME=$(echo ${GITHUB_REPOSITORY}| awk -F "/" '{print $1}')
          echo "REPO=${ORGANIZATION_NAME,,}" >> ${GITHUB_ENV}

      - name: Echo env
        run: |
          echo "REPO: ${{ env.REPO }}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin


  calico-single-stack-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: calico-single-stack-centos7
        run: |
          echo "calico-single-stack-centos7"
#          CONTAINER_TAG="$(git describe --tags --abbrev=8 --dirty)-e2e"
#          HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1 }'`
#          TAG_SECOND_PART=`echo ${CONTAINER_TAG}|awk  -F "-" '{print $2 }'`
#          if [[ ${TAG_SECOND_PART} =~ rc[0-9]+ ]];then
#            HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1"-"$2 }'`
#          fi
#          echo ${{ runner.name }}
#          echo "${HELM_CHART_VERSION}"
#          echo "${CONTAINER_TAG}"
#          bash hack/e2e.sh "${HELM_CHART_VERSION}" "${CONTAINER_TAG}" ${{ runner.name }} "${VSPHERE_USER}" "${VSPHERE_PASSWD}" "${AMD_ROOT_PASSWORD}" "${KYLIN_VM_PASSWORD}" "NIGHTLY"

  add-remove-worker-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: add-remove-worker-centos7
        run: |
          echo "add-remove-worker-centos7"
#          CONTAINER_TAG="$(git describe --tags --abbrev=8 --dirty)-e2e"
#          HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1 }'`
#          TAG_SECOND_PART=`echo ${CONTAINER_TAG}|awk  -F "-" '{print $2 }'`
#          if [[ ${TAG_SECOND_PART} =~ rc[0-9]+ ]];then
#            HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1"-"$2 }'`
#          fi
#          echo ${{ runner.name }}
#          echo "${HELM_CHART_VERSION}"
#          echo "${CONTAINER_TAG}"
#          bash hack/e2e.sh "${HELM_CHART_VERSION}" "${CONTAINER_TAG}" ${{ runner.name }} "${VSPHERE_USER}" "${VSPHERE_PASSWD}" "${AMD_ROOT_PASSWORD}" "${KYLIN_VM_PASSWORD}" "NETWORK"

  update-k8s-version-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: update-k8s-version-centos7
        run: |
          echo "update-k8s-version-centos7"

  os-compatibility-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: os-compatibility-centos7
        run: |
          echo "os-compatibility-centos7"

  os-compatibility-redhat7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: os-compatibility-redhat7
        run: |
          echo "os-compatibility-redhat7"

  os-compatibility-redhat8:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: os-compatibility-redhat8
        run: |
          echo "os-compatibility-redhat8"

  os-compatibility-kylin:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: os-compatibility-kylin
        run: |
          echo "os-compatibility-kylin"

  kubean-function-e2e-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: kubean-function-e2e-centos7
        run: |
          echo "kubean-function-e2e-centos7"

  reset-cluster-e2e-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: reset-cluster-e2e-centos7
        run: |
          echo "reset-cluster-e2e-centos7"

  install-with-docker-e2e-centos7:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: install-with-docker-e2e-centos7
        run: |
          echo "install-with-docker-e2e-centos7"

  calico-dual-stack-e2e-redhat8:
    needs: [calico-single-stack-centos7, add-remove-worker-centos7, reset-cluster-e2e-centos7, kubean-function-e2e-centos7, os-compatibility-kylin, os-compatibility-redhat8, os-compatibility-redhat7, os-compatibility-centos7, update-k8s-version-centos7, install-with-docker-e2e-centos7]
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: calico-dual-stack-e2e-redhat8
        run: |
          echo "calico-dual-stack-e2e-redhat8"

  cilium-cluster-e2e-redhat8:
    needs: [calico-single-stack-centos7, add-remove-worker-centos7, reset-cluster-e2e-centos7, kubean-function-e2e-centos7, os-compatibility-kylin, os-compatibility-redhat8, os-compatibility-redhat7, os-compatibility-centos7, update-k8s-version-centos7, install-with-docker-e2e-centos7]
    runs-on: [self-hosted, online]
    continue-on-error: true
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: cilium-cluster-e2e-redhat8
        run: |
          echo "cilium-cluster-e2e-redhat8"